### ISSUE TITLE
`melt.data.frame()` Forcing the `variable` column to be of type character

### ISSUE THREAD

**Issue by mr-majkel** [hadley/reshape#71]
Hi,
There is a couple years old [question on StackOverflow](http://stackoverflow.com/questions/7423116/how-to-change-the-melt-data-frame-function-in-reshape2-package-returned-variabl) that describes a  slight nuisance of `melt.data.frame()` returning `variable` column as a factor and not as a character. Is it possible to include a switch to control this behavior?

**Comment by hadley** [comment]
reshape/reshape2 is no longer under active development so probably not, sorry.
